usd.amount.xpath=(//*[contains(@class,'calculatorstyles__InputWrapper')])[1]//input
token.dropdown.xpath=((//*[contains(@class,'calculatorstyles__InputWrapper')])[1]/following::input[contains(@class,'auto-complete')])[1]
token.amount.xpath=(//*[contains(@class,'calculatorstyles__InputWrapper')])[2]//input
eth.token.xpath=//*[contains(@class,'auto-completestyles__Option')][text()='Ethereum']
xrp.token.xpath=//*[contains(@class,'auto-completestyles__Option')][text()='XRP']
btc.token.xpath=//*[contains(@class,'auto-completestyles__Option')][text()='Bitcoin']